elasticsearch:
  image: "elasticsearch:1.7.3"
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: "stackhub/logstash:latest"
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    # otherwise logstash will keep sending its own logs to itself over and
    # over... not fun
    LOGSPOUT: ignore
  command: -f /etc/logstash.sample.conf
  links:
    - elasticsearch:elasticsearch
kibana:
  image: stackhub/kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logspout:
  image: "stackhub/logspout:latest"
  net: container:logstash
  environment:
    DEBUG: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: syslog://localhost:5000