# Maintained by StackEngine
elasticsearch:
  # The elasticsearch image works well for this.
  image: elasticsearch:latest
  ports:
    - "9200:9200"
logstash:
  image: stackhub/logstash:latest
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  image: stackhub/kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch